/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAT_H_RPCGEN
#define _CHAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Info_itf {
	int id;
	char name[256];
};
typedef struct Info_itf Info_itf;

struct Message_itf {
	int id;
	char name[256];
	char message[256];
};
typedef struct Message_itf Message_itf;

#define CHAT_PROG 0x20000001
#define CHAT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define join 1
extern  int * join_1(Info_itf *, CLIENT *);
extern  int * join_1_svc(Info_itf *, struct svc_req *);
#define print_clients 2
extern  void * print_clients_1(void *, CLIENT *);
extern  void * print_clients_1_svc(void *, struct svc_req *);
#define update 3
extern  Message_itf * update_1(int *, CLIENT *);
extern  Message_itf * update_1_svc(int *, struct svc_req *);
#define send_message 4
extern  void * send_message_1(Message_itf *, CLIENT *);
extern  void * send_message_1_svc(Message_itf *, struct svc_req *);
#define update_client 5
extern  Info_itf * update_client_1(int *, CLIENT *);
extern  Info_itf * update_client_1_svc(int *, struct svc_req *);
#define print_messages 6
extern  Message_itf * print_messages_1(int *, CLIENT *);
extern  Message_itf * print_messages_1_svc(int *, struct svc_req *);
extern int chat_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define join 1
extern  int * join_1();
extern  int * join_1_svc();
#define print_clients 2
extern  void * print_clients_1();
extern  void * print_clients_1_svc();
#define update 3
extern  Message_itf * update_1();
extern  Message_itf * update_1_svc();
#define send_message 4
extern  void * send_message_1();
extern  void * send_message_1_svc();
#define update_client 5
extern  Info_itf * update_client_1();
extern  Info_itf * update_client_1_svc();
#define print_messages 6
extern  Message_itf * print_messages_1();
extern  Message_itf * print_messages_1_svc();
extern int chat_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Info_itf (XDR *, Info_itf*);
extern  bool_t xdr_Message_itf (XDR *, Message_itf*);

#else /* K&R C */
extern bool_t xdr_Info_itf ();
extern bool_t xdr_Message_itf ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHAT_H_RPCGEN */
